### ISSUE TITLE
There is no unique or exclusion constraint matching the ON CONFLICT specification

### ISSUE THREAD

**Issue by theresthatguy** [Brideau/pokelyzer#16]
After recently updating to allow for spawn "eras" I am getting this error in my terminal.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/theresthatguy/Pokemon/mapdb/pogom/search.py", line 159, in search_thread
    parse_map(response_dict, i, step, step_location)
  File "/home/theresthatguy/Pokemon/mapdb/pogom/models.py", line 236, in parse_map
    logPokemonDb(p)
  File "/home/theresthatguy/Pokemon/mapdb/pogom/customLog.py", line 59, in logPokemonDb
    cursor.execute(query, data)
ProgrammingError: there is no unique or exclusion constraint matching the ON CONFLICT specification
```

**Comment by Brideau** [comment]
Have a look at the patches listed in the main Readme file - they should take care of that.

**Comment by Brideau** [comment]
I'm going to rename this issue and leave the ticket open for a bit so that other people can find it easier.
