### ISSUE TITLE
Error conflicting options string(s)

### ISSUE THREAD

**Issue by theresthatguy** [Brideau/pokelyzer#2]
```
parser.add_argument('-t', '--threads', help='Number of search threads', required=False, type=int, default=5, dest='num_threads')
```

Adding line above to /pogom/utils.py causes this error: 

Traceback (most recent call last):
  File "runserver.py", line 13, in <module>
    from pogom.app import Pogom
  File "/home/theresthatguy/Pokemon/pogoDB/pogom/app.py", line 11, in <module>
    from .models import Pokemon, Gym, Pokestop, ScannedLocation
  File "/home/theresthatguy/Pokemon/pogoDB/pogom/models.py", line 13, in <module>
    from .customLog import printPokemon, logPokemonDb
  File "/home/theresthatguy/Pokemon/pogoDB/pogom/customLog.py", line 7, in <module>
    args = get_args()
  File "/home/theresthatguy/Pokemon/pogoDB/pogom/utils.py", line 61, in get_args
    parser.add_argument('-t', '--threads', help='Number of search threads', required=False, type=int, default=5, dest='num_threads')
  File "/usr/lib/python2.7/argparse.py", line 1308, in add_argument
    return self._add_action(action)
  File "/usr/lib/python2.7/argparse.py", line 1682, in _add_action
    self._optionals._add_action(action)
  File "/usr/lib/python2.7/argparse.py", line 1509, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/usr/lib/python2.7/argparse.py", line 1322, in _add_action
    self._check_conflict(action)
  File "/usr/lib/python2.7/argparse.py", line 1460, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/usr/lib/python2.7/argparse.py", line 1467, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -t/--threads: conflicting option string(s): -t, --threads

And if I comment it out, it's all good.

**Comment by marvin-bitterlich** [comment]
You added that line a second time? That would be the problem...
https://github.com/Brideau/pokelyzer/blob/master/sample_utils.py#L59 already exists
