### ISSUE TITLE
Error after Jul 28, 2016 ~12PM EDT patch

### ISSUE THREAD

**Issue by brendan-mccoy** [Brideau/pokelyzer#4]
I did 

`DROP TABLE public.pokemon_info;`

and then restored from the newest backup.

However, I am now getting many instances of this error:

```
Exception in thread search_thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/ubuntu/PokemonGo-Map/pogom/search.py", line 159, in search_thread
    parse_map(response_dict, i, step, step_location)
  File "/home/ubuntu/PokemonGo-Map/pogom/models.py", line 235, in parse_map
    logPokemonDb(p)
  File "/home/ubuntu/PokemonGo-Map/pogom/customLog.py", line 59, in logPokemonDb
    cursor.execute(query, data)
IntegrityError: duplicate key value violates unique constraint "id_primary_key"
DETAIL:  Key (id)=(113) already exists.


Exception in thread search_thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/ubuntu/PokemonGo-Map/pogom/search.py", line 159, in search_thread
    parse_map(response_dict, i, step, step_location)
  File "/home/ubuntu/PokemonGo-Map/pogom/models.py", line 235, in parse_map
    logPokemonDb(p)
  File "/home/ubuntu/PokemonGo-Map/pogom/customLog.py", line 59, in logPokemonDb
    cursor.execute(query, data)
IntegrityError: duplicate key value violates unique constraint "id_primary_key"
DETAIL:  Key (id)=(116) already exists.
```

Is this a sign that something went wrong in the patch or an indicator of something else? Things were working fine before.

**Comment by brendan-mccoy** [comment]
I'm a dummy and didn't use the patch, I used the backup.

**Comment by brendan-mccoy** [comment]
I rebuilt the database and properly patched it, and I'm still getting this identical error, it seems.

**Comment by brendan-mccoy** [comment]
So it seems the python script was trying to record new encounters using ID numbers for encounters that already happened.  Dunno what caused that but wiping my data fixed it.
