### ISSUE TITLE
Runtime Exception

### ISSUE THREAD

**Issue by maxwell-gregory** [Brideau/pokelyzer#47]
Any leads or pointers as to what this might be? 

```
pi@raspberrypi:~/rep/pokelyzer $ DB_NAME='pokemon_go' DB_USER='pokemon_go_role' DB_PASS='pogomystic' DB_PORT=5432 WS_PORT=9876 ERA=2  node app.js | bunyan -l debug
[2016-08-02T05:36:30.213Z]  INFO: MainApp/14906 on raspberrypi: Running server on port 9876
[2016-08-02T05:36:40.360Z] DEBUG: MainApp/14906 on raspberrypi:  (time_until_hidden_ms=874787, last_modified_time=1470116199793, disappear_time=1470117074, pokemon_id=32, latitude=37.54317944859647, spawnpoint_id=808fc0be465, encounter_id=ODM5MTAyMzQ1NDA1NjA3MjQ3Nw==, longitude=-121.97374944075166, pokemon_go_era=2, hidden_time_unix_s=1470117074, hidden_time_utc="2016-08-02 05:51:14", latitude_jittered=37.542733607620825, longitude_jittered=-121.97373263788748)
[2016-08-02T05:36:40.424Z]  INFO: MainApp/14906 on raspberrypi: Pokemon with ID 32 found.
[2016-08-02T05:36:40.424Z] DEBUG: MainApp/14906 on raspberrypi: INSERT INTO spotted_pokemon (           encounter_id,           last_modified_time,           time_until_hidden_ms,           hidden_time_unix_s,           hidden_time_utc,           spawnpoint_id,           longitude,           latitude,           pokemon_id,           longitude_jittered,           latitude_jittered,           pokemon_go_era)         VALUES (           'ODM5MTAyMzQ1NDA1NjA3MjQ3Nw=='::varchar,           1470116199793::bigint,           874787::bigint,           1470117074::bigint,           '2016-08-02 05:51:14'::timestamp,           '808fc0be465'::varchar,           -121.97374944075166::double precision,           37.54317944859647::double precision,           32::smallint,           -121.97373263788748::double precision,           37.542733607620825::double precision,           2::integer         )         ON CONFLICT (encounter_id)         DO UPDATE           SET last_modified_time = EXCLUDED.last_modified_time,           time_until_hidden_ms = EXCLUDED.time_until_hidden_ms,           hidden_time_unix_s = EXCLUDED.hidden_time_unix_s,           hidden_time_utc = EXCLUDED.hidden_time_utc;
[2016-08-02T05:36:40.447Z] ERROR: MainApp/14906 on raspberrypi:
    Error running query { error: syntax error at or near "ON"
        at Connection.parseE (/home/pi/rep/pokelyzer/node_modules/pg/lib/connection.js:551:11)
        at Connection.parseMessage (/home/pi/rep/pokelyzer/node_modules/pg/lib/connection.js:378:17)
        at Socket.<anonymous> (/home/pi/rep/pokelyzer/node_modules/pg/lib/connection.js:117:22)
        at emitOne (events.js:96:13)
        at Socket.emit (events.js:188:7)
        at readableAddChunk (_stream_readable.js:172:18)
        at Socket.Readable.push (_stream_readable.js:130:10)
        at TCP.onread (net.js:542:20)
      name: 'error',
      length: 85,
      severity: 'ERROR',
      code: '42601',
      detail: undefined,
      hint: undefined,
      position: '838',
      internalPosition: undefined,
      internalQuery: undefined,
      where: undefined,
      schema: undefined,
      table: undefined,
      column: undefined,
      dataType: undefined,
      constraint: undefined,
      file: 'scan.l',
      line: '1052',
      routine: 'scanner_yyerror' }
```

Happens everytime it finds a pokemon

**Comment by Brideau** [comment]
What version of Postgres are you running? Somebody had the same error because they were running 9.4 instead of 9.5

**Comment by maxwell-gregory** [comment]
So this was hell to fix. That error was because of my postgres version, however I am running this on a Raspberry Pi. There is no apt-get package for Postgres 9.5 nor Postgres9.5-Postgis2.2. After using unstable debian builds and a few hundred dependencies later I got it run error free. I'd try and document it but it was too many steps...

@Brideau Your code is actually very RPi unfriendly lol. I know this wasn't your intention but if you want to make this cover more platforms (i think it might not just be RPi) i recommend seeing if you can use older code

**Comment by Brideau** [comment]
Damn, that sounds rough! Yeah the query does take advantage of syntax in 9.5, and I could look into re-writing it so it also works with 9.4 I'll add it to the list of feature requests but it's not going to be super high on the priority list for now.
