### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by talentedmrripley** [Brideau/pokelyzer#77]
I cloned the repo today.  Postgres is setup and working, tables have been imported.  I also cloned PokemonGo-Map today and its running as expected.  Below is all I see in the console for pokelyzer.  I've checked also and nothing is getting added to the database.  

TypeError: undefined is not a function
    at Pool.connect (/home/ripley/pokelyzer/node_modules/pg/node_modules/pg-pool/index.js:54:10)
    at /home/ripley/pokelyzer/app.js:57:12
    at Layer.handle [as handle_request](/home/ripley/pokelyzer/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/ripley/pokelyzer/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/ripley/pokelyzer/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request](/home/ripley/pokelyzer/node_modules/express/lib/router/layer.js:95:5)
    at /home/ripley/pokelyzer/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/home/ripley/pokelyzer/node_modules/express/lib/router/index.js:330:12)
    at next (/home/ripley/pokelyzer/node_modules/express/lib/router/index.js:271:10)
    at /home/ripley/pokelyzer/node_modules/body-parser/lib/read.js:129:5

This same message is added shown over and over again, I'm assuming for every found Pokemon.

**Comment by Brideau** [comment]
Can you post the commands you're using to run each? And are you using the develop branch of PokemonGo-Map?

**Comment by talentedmrripley** [comment]
pokelyzer:

`DB_NAME='pokemon_go' DB_USER='pokemon_go_role' DB_PASS='********' DB_PORT=5432 WS_PORT=9876 ERA=3 node app.js`

config.ini:

```
# Authentication settings
#auth-service: google          # ptc (default) or google
#username: 
#password: 

# Database settings
db-type: mysql        # sqlite (default) or mysql
db-host: localhost              # required for mysql
db-name: pgo_map               # required for mysql
db-user: pgo               # required for mysql
db-pass: *****               # required for mysql

# Search settings
#location:
#no-gyms:               # disables gym scanning (default false)
#no-pokemon:            # disables pokemon scanning (default false)
#no-pokestops:          # disables pokestop scanning (default false)
#num-threads: 3         # number of search threads (default 1)
#scan-delay: 5           # default 5
#step-limit:            # default 12

# Misc
gmaps-key: *****            # your Google Maps API key
webhook: http://localhost:9876               # webhook URL (including http://)

# Webserver settings
host: 0.0.0.0                  # address to listen on (default 127.0.0.1)
#port: 5005                  # port to listen on (default 5000)
```

beehive startup script:

```
#!/usr/bin/env bash
nohup python runserver.py -os -l '40.037255 -105.254726' -P 5002 &
sleep 0.5; nohup python runserver.py -ns -l '*' -st 5 -a ptc -u *-p '*' &
sleep 0.5; nohup python runserver.py -ns -l '*' -st 5 -a ptc -u *-p '*' &
sleep 0.5; nohup python runserver.py -ns -l '*' -st 5 -a ptc -u *-p '*' &
sleep 0.5; nohup python runserver.py -ns -l '*' -st 5 -a ptc -u *-p '*' &
sleep 0.5; nohup python runserver.py -ns -l '*' -st 5 -a ptc -u 8-p '*' &
sleep 0.5; nohup python runserver.py -ns -l '*' -st 5 -a ptc -u *-p '*' &
sleep 0.5; nohup python runserver.py -ns -l '*' -st 5 -a ptc -u *-p '*' &
sleep 0.5; nohup python runserver.py -ns -l '*' -st 5 -a ptc -u *-p '*' &
sleep 0.5; nohup python runserver.py -ns -l '*' -st 5 -a ptc -u *-p '*' &
sleep 0.5; nohup python runserver.py -ns -l '*' -st 5 -a ptc -u *-p '*' &
sleep 0.5; nohup python runserver.py -ns -l '*' -st 5 -a ptc -u *-p '*' &
sleep 0.5; nohup python runserver.py -ns -l '*' -st 5 -a ptc -u *-p '*' &
sleep 0.5; nohup python runserver.py -ns -l '*' -st 5 -a ptc -u *-p '*' &
sleep 0.5; nohup python runserver.py -ns -l '*' -st 5 -a ptc -u *-p '*' &
sleep 0.5; nohup python runserver.py -ns -l '*' -st 5 -a ptc -u *-p '*' &
sleep 0.5; nohup python runserver.py -ns -l '*' -st 5 -a ptc -u *-p '*' &
sleep 0.5; nohup python runserver.py -ns -l '*' -st 5 -a ptc -u *-p '*' &
sleep 0.5; nohup python runserver.py -ns -l '*' -st 5 -a ptc -u *-p '*' &
sleep 0.5; nohup python runserver.py -ns -l '*' -st 5 -a ptc -u *-p '*' &
```

I am using the develop branch of PokemonGo-Map

**Comment by talentedmrripley** [comment]
I was also having this issue - https://github.com/Brideau/pokelyzer/issues/45 and edited the file to remove the reference and it seemed to solve my issue.  Not sure if this is related.

**Comment by Brideau** [comment]
Can you uncomment the line `console.log(query_string);` and post the results of that? That might give me a hint of what's causing it.

**Comment by talentedmrripley** [comment]
I uncommented it in app.js, but the output looks like same:

```
TypeError: undefined is not a function
    at Pool.connect (/home/ripley/pokelyzer/node_modules/pg/node_modules/pg-pool/index.js:54:10)
    at /home/ripley/pokelyzer/app.js:57:12
    at Layer.handle [as handle_request] (/home/ripley/pokelyzer/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/ripley/pokelyzer/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/ripley/pokelyzer/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/ripley/pokelyzer/node_modules/express/lib/router/layer.js:95:5)
    at /home/ripley/pokelyzer/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/home/ripley/pokelyzer/node_modules/express/lib/router/index.js:330:12)
    at next (/home/ripley/pokelyzer/node_modules/express/lib/router/index.js:271:10)
    at /home/ripley/pokelyzer/node_modules/body-parser/lib/read.js:129:5
```

 I also tried running just a single search instead of the beehive, on a different webhook port, and got the same results.

**Comment by Brideau** [comment]
Looks like the error is being thrown before you get to the query string part.  This seems to be a common error with older versions of the 'pg' library. Can you go into the node_modules folder, then to "pg" and open the package.json file. Let me know what version of pg is installed - it should say near the top.

**Comment by talentedmrripley** [comment]
"name": "pg",
"version": "6.0.3"

I tried `npm install pg` and got to version 6.1.  Tried running pokelyzer again, had to comment out the Promise line in index.js again.  Similar results though:

```
TypeError: undefined is not a function
    at Pool.connect (/home/ripley/pokelyzer/node_modules/pg/node_modules/pg-pool/index.js:55:10)
    at /home/ripley/pokelyzer/app.js:57:12
    at Layer.handle [as handle_request] (/home/ripley/pokelyzer/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/ripley/pokelyzer/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/ripley/pokelyzer/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/ripley/pokelyzer/node_modules/express/lib/router/layer.js:95:5)
    at /home/ripley/pokelyzer/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/home/ripley/pokelyzer/node_modules/express/lib/router/index.js:330:12)
    at next (/home/ripley/pokelyzer/node_modules/express/lib/router/index.js:271:10)
    at /home/ripley/pokelyzer/node_modules/body-parser/lib/read.js:129:5
```

**Comment by Brideau** [comment]
This is baffling. I might even recommend you post this over in https://github.com/brianc/node-postgres/ because I can't replicate it, and they might have seen it before.

**Comment by brianc** [comment]
You'll need to polyfill a promise implementation if you're in an older node environment.

https://github.com/brianc/node-pg-pool#bring-your-own-promise

In this case this should probably be done within the pokelyzer code base.  Sorry for any confusion!

**Comment by Brideau** [comment]
Ah, that makes sense. Strange that nobody else had this issue. What version of node are you running this on

**Comment by Brideau** [comment]
(That was a question for @talentedmrripley)

**Comment by talentedmrripley** [comment]
dpks -s nodejs says Version: 0.10.46-1nodesource1~trusty1

**Comment by Brideau** [comment]
Ahh, well there's the problem! You'll need the 4.X version to run this.

**Comment by talentedmrripley** [comment]
My bad on the version.  Didn't even think to check that earlier.

Success!!

```
[2016-08-11T16:54:11-06:00] Pokemon with ID 13 found.
[2016-08-11T16:54:11-06:00] Pokemon with ID 48 found.
[2016-08-11T16:54:13-06:00] Pokemon with ID 56 found.
[2016-08-11T16:54:13-06:00] Pokemon with ID 104 found.
[2016-08-11T16:54:13-06:00] Pokemon with ID 46 found.
```

I wonder if that could have been the issue for https://github.com/Brideau/pokelyzer/issues/45 also?  Getting 4.x solved both issues for me.
